arxiv_cats = {
  "astro-ph": "Astrophysics",
  "cond-mat": "Condensed Matter",
  "gr-qc": "General Relativity and Quantum Cosmology",
  "hep-ex": "High Energy Physics - Experiment",
  "hep-lat": "High Energy Physics - Lattice",
  "hep-ph": "High Energy Physics - Phenomenology",
  "hep-th": "High Energy Physics - Theory",
  "math-ph": "Mathematical Physics",
  "nlin": "Nonlinear Sciences",
  "nucl-ex": "Nuclear Experiment",
  "nucl-th": "Nuclear Theory",
  "physics": "Physics (cross-listing only)",
  "quant-ph": "Quantum Physics",
  "math.AC": "Mathematics - Commutative Algebra",
  "math.AG": "Mathematics - Algebraic Geometry",
  "math.AP": "Mathematics - Analysis of PDEs",
  "math.AT": "Mathematics - Algebraic Topology",
  "math.CA": "Mathematics - Classical Analysis and ODEs",
  "math.CO": "Mathematics - Combinatorics",
  "math.CT": "Mathematics - Category Theory",
  "math.CV": "Mathematics - Complex Variables",
  "math.DG": "Mathematics - Differential Geometry",
  "math.DS": "Mathematics - Dynamical Systems",
  "math.FA": "Mathematics - Functional Analysis",
  "math.GM": "Mathematics - General Mathematics",
  "math.GN": "Mathematics - General Topology",
  "math.GR": "Mathematics - Group Theory",
  "math.GT": "Mathematics - Geometric Topology",
  "math.HO": "Mathematics - History and Overview",
  "math.IT": "Mathematics - Information Theory",
  "math.KT": "Mathematics - Knot Theory",
  "math.LO": "Mathematics - Logic",
  "math.MG": "Mathematics - Metric Geometry",
  "math.MP": "Mathematics - Mathematical Physics",
  "math.NT": "Mathematics - Number Theory",
  "math.OA": "Mathematics - Operator Algebras",
  "math.OC": "Mathematics - Optimization and Control",
  "math.PR": "Mathematics - Probability",
  "math.QA": "Mathematics - Quantum Algebra",
  "math.RT": "Mathematics - Representation Theory",
  "math.SG": "Mathematics - Symplectic Geometry",
  "math.SP": "Mathematics - Spectral Theory",
  "math.ST": "Mathematics - Statistics Theory",
  "cs.AI": "Computer Science - Artificial Intelligence",
  "cs.AR": "Computer Science - Hardware Architecture",
  "cs.CC": "Computer Science - Computational Complexity",
  "cs.CE": "Computer Science - Computational Engineering, Finance, and Science",
  "cs.CG": "Computer Science - Computational Geometry",
  "cs.CL": "Computer Science - Computation and Language",
  "cs.CR": "Computer Science - Cryptography and Security",
  "cs.CV": "Computer Science - Computer Vision and Pattern Recognition",
  "cs.CY": "Computer Science - Computers and Society",
  "cs.DB": "Computer Science - Databases",
  "cs.DC": "Computer Science - Distributed, Parallel, and Cluster Computing",
  "cs.DL": "Computer Science - Digital Libraries",
  "cs.DM": "Computer Science - Discrete Mathematics",
  "cs.DS": "Computer Science - Data Structures and Algorithms",
  "cs.ET": "Computer Science - Emerging Technologies",
  "cs.FC": "Computer Science - Formal Languages and Automata Theory",
  "cs.GL": "Computer Science - General Literature",
  "cs.GR": "Computer Science - Graphics",
  "cs.GT": "Computer Science - Computer Science and Game Theory",
  "cs.HC": "Computer Science - Human-Computer Interaction",
  "cs.IR": "Computer Science - Information Retrieval",
  "cs.IT": "Computer Science - Information Theory",
  "cs.LG": "Computer Science - Machine Learning",
  "cs.LO": "Computer Science - Logic in Computer Science",
  "cs.MA": "Computer Science - Multiagent Systems",
  "cs.MC": "Computer Science - Mathematical Aspects of Computer Science",
  "cs.MM": "Computer Science - Multimedia",
  "cs.MS": "Computer Science - Mathematical Software",
  "cs.NA": "Computer Science - Numerical Analysis",
  "cs.NE": "Computer Science - Neural and Evolutionary Computing",
  "cs.NI": "Computer Science - Networking and Internet Architecture",
  "cs.OS": "Computer Science - Operating Systems",
  "cs.PF": "Computer Science - Performance",
  "cs.PL": "Computer Science - Programming Languages",
  "cs.RO": "Computer Science - Robotics",
  "cs.SC": "Computer Science - Symbolic Computation",
  "cs.SD": "Computer Science - Sound",
  "cs.SE": "Computer Science - Software Engineering",
  "cs.SI": "Computer Science - Social and Information Networks",
  "cs.SY": "Computer Science - Systems and Control",
  "eess.AS": "Electrical Engineering and Systems Science - Audio and Speech Processing",
  "eess.IV": "Electrical Engineering and Systems Science - Image and Video Processing",
  "eess.SP": "Electrical Engineering and Systems Science - Signal Processing",
  "eess.SY": "Electrical Engineering and Systems Science - Systems and Control",
  "econ.EM": "Economics - Econometrics",
  "econ.GN": "Economics - General Economics",
  "econ.TH": "Economics - Theoretical Economics",
  "q-bio.BM": "Quantitative Biology - Biomolecules",
  "q-bio.CB": "Quantitative Biology - Cell Behavior",
  "q-bio.GN": "Quantitative Biology - Genomics",
  "q-bio.MN": "Quantitative Biology - Molecular Networks",
  "q-bio.NC": "Quantitative Biology - Neurons and Cognition",
  "q-bio.PE": "Quantitative Biology - Population Dynamics",
  "q-bio.QM": "Quantitative Biology - Quantitative Methods",
  "q-bio.SC": "Quantitative Biology - Subcellular Processes",
  "q-bio.TO": "Quantitative Biology - Tissues and Organs",
  "q-fin.CP": "Quantitative Finance - Computational Finance",
  "q-fin.EC": "Quantitative Finance - Econometrics",
  "q-fin.GN": "Quantitative Finance - General Finance",
  "q-fin.PR": "Quantitative Finance - Pricing of Securities",
  "q-fin.RM": "Quantitative Finance - Risk Management",
  "q-fin.ST": "Quantitative Finance - Statistical Finance",
  "q-fin.TR": "Quantitative Finance - Trading and Market Microstructure",
  "stat.AP": "Statistics - Applications",
  "stat.CO": "Statistics - Computation",
  "stat.ME": "Statistics - Methodology",
  "stat.ML": "Statistics - Machine Learning",
  "stat.OT": "Statistics - Other Statistics",
  "stat.TH": "Statistics - Theory"
}